In [1]:
import numpy as np

The Basics


In [2]:
a= np.array([1,3,8])
b= np.array([5,7,11])

In [13]:
print(a*b)

[ 5 21 88]


In [14]:
c=np.array([[2.0,5.0,8.7],[1.0,3.4,4.8]])
print(c)

[[2.  5.  8.7]
 [1.  3.4 4.8]]


In [17]:
#  Get Dimsension 
c.ndim

2

In [19]:
#  Get Shape
c.shape

(2, 3)

In [22]:
#  Get Type 
b.dtype

dtype('int64')

In [35]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype= 'int16')
d.dtype

dtype('int16')

In [27]:
#  Get Size 
print(a.itemsize)
print(d.itemsize)

8
2


In [28]:
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
# Get Total Size
print(a.size*a.itemsize)
print(b.size*b.itemsize)
print(c.size*c.itemsize)
print(d.size*d.itemsize)

24
24
48
18


or...


In [41]:
# Get Total Size 

print(a.nbytes)
print(b.nbytes)
print(c.nbytes)
print(d.nbytes)

24
24
48
18


Initializing Different Types of Array

In [46]:
#  All 0s Matrix

np.zeros((2,3,3,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [ ]:
#  All 1s Matrix

np.ones((2,3,3,5), dtype='int32')

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int32)

In [49]:
# Any other numbers -> ((shape),(number))

np.full((2,3,5,4),(88))

array([[[[88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88]],

        [[88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88]],

        [[88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88]]],


       [[[88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88]],

        [[88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88]],

        [[88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88]]]])

In [57]:
# Any other numbers -> (full_like)

np.full((d.shape), (4,5,6))

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

or...

In [58]:
# Any other numbers -> (full_like)

np.full_like(d, (4,5,6))

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]], dtype=int16)

In [62]:
#  Random Decimal Numbers

np.random.rand(4,2,3)

array([[[0.10312563, 0.01267999, 0.33595666],
        [0.89766651, 0.98523828, 0.62217461]],

       [[0.88756348, 0.83531373, 0.60699861],
        [0.87016907, 0.18423916, 0.25164406]],

       [[0.58608587, 0.64779212, 0.17062545],
        [0.90867071, 0.25947669, 0.29911159]],

       [[0.8086691 , 0.56129322, 0.7372606 ],
        [0.9089931 , 0.47711568, 0.60220775]]])

In [71]:
np.random.sample(d.shape)

array([[0.55078761, 0.46498135, 0.00949634],
       [0.43940818, 0.58385936, 0.64174887],
       [0.3313542 , 0.34366872, 0.34346284]])

In [65]:
#  Array in the range [10, 20) with values (4, 2, 3)

w_uniform = np.random.uniform(low=10.0, high=20.0, size=(4, 2, 3))
w_uniform

array([[[13.17178199, 11.45867332, 15.95020334],
        [14.70557501, 19.60366793, 17.78822254]],

       [[16.22307898, 16.95222612, 12.79624811],
        [14.09607586, 12.94551546, 16.55483111]],

       [[19.49136994, 15.62951266, 15.01194783],
        [16.05084679, 11.75124529, 14.8168698 ]],

       [[15.91904697, 17.79626574, 12.49406676],
        [10.49897335, 17.31464834, 13.50907943]]])

In [76]:
#  Random Integer Values

np.random.randint(88,140, size=(3,4,7))

array([[[124, 128,  98, 122, 119, 120,  96],
        [116, 100, 101,  95, 104, 116, 135],
        [113,  96, 134, 101,  92, 114, 112],
        [136, 113,  97, 115,  97, 108, 114]],

       [[118,  99, 138, 128, 117, 114, 100],
        [117, 104, 125, 103, 118, 123,  98],
        [116, 114,  88, 102,  91, 111, 105],
        [103, 136, 110, 112, 127, 100, 103]],

       [[ 89, 103, 114, 106,  92,  95, 132],
        [ 91,  91, 130, 124, 114, 109,  99],
        [123, 139, 130, 118, 115, 105, 104],
        [ 92, 110, 107, 121, 119, 103,  89]]], dtype=int32)

In [78]:
#  The Identity Matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
#  Repeat an array

arr= np.array([[1,2,3],[2,3,4],[3,4,5]])
R1=np.repeat(arr,3, axis=0)
print(R1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [2 3 4]
 [2 3 4]
 [2 3 4]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [98]:
x=np.ones((5,5))
print(x)

z=np.zeros((3,3))
z[1,1]=9
print(z)

x[1:-1,1:-1]=z
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be Careful When Copying Arrays!!!