In [1]:
import numpy as np

Mathematics

In [2]:
a=np.array([1,2,3])

In [5]:
print(a*2)
print(a+2)
print(a-19)
print(a/2)

[2 4 6]
[3 4 5]
[-18 -17 -16]
[0.5 1.  1.5]


In [6]:
b= np.array([1,0,1])

In [9]:
print(a+b)
print(a-b)
print(a*2)
print(b/a)

[2 2 4]
[0 2 2]
[2 4 6]
[1.         0.         0.33333333]


In [14]:
#  Take the radian 

print(np.radians(a))

[0.01745329 0.03490659 0.05235988]


In [15]:
#  Take the sin

print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [16]:
# Take the cos

print(np.cos(b))

[0.54030231 1.         0.54030231]


In [17]:
#  Take the tan

print(np.tan(a))

[ 1.55740772 -2.18503986 -0.14254654]


In [21]:
#  Take the cot 

print((np.tan(b))*(-1))

[-1.55740772 -0.         -1.55740772]


Lineer Algebra

In [25]:
x= np.ones((5,9))
print(x)

y=np.full((9,7),5)
print(y)

np.matmul(x,y)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]


array([[45., 45., 45., 45., 45., 45., 45.],
       [45., 45., 45., 45., 45., 45., 45.],
       [45., 45., 45., 45., 45., 45., 45.],
       [45., 45., 45., 45., 45., 45., 45.],
       [45., 45., 45., 45., 45., 45., 45.]])

In [30]:
#  Find the determinant
g=np.identity(3)
np.linalg.det(g)

np.float64(1.0)

In [31]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...


#### Statictics

In [35]:
stats= np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [45]:
#  Take the min 

print(np.min(stats))
print(np.min(stats, axis=0)) #  The “Axis=0” command retrieves the row containing the smallest/largest value.

1
[1 2 3]


In [46]:
#  Take the max
print(np.max(stats))
print(np.max(stats, axis=1)) #  The "Axis=1" command returns the maximum/minimum value of each row.

6
[3 6]


In [38]:
#  Take the mean

np.mean(stats)

np.float64(3.5)

In [39]:
#  Take the median

np.median(stats)

np.float64(3.5)

In [52]:
#  Sum all values

print(np.sum(stats))
print(np.sum(stats, axis=0)) #  With the value “Axis=0”, we print the totals of all columns separately.
print(np.sum(stats, axis=1)) #  With the value "Axis=1", we print the totals of all rows separately.

21
[5 7 9]
[ 6 15]
