In [7]:
import numpy as np

The Basics


In [8]:
a= np.array([1,3,8])
b= np.array([5,7,11])

In [9]:
print(a*b)

[ 5 21 88]


In [10]:
c=np.array([[2.0,5.0,8.7],[1.0,3.4,4.8]])
print(c)

[[2.  5.  8.7]
 [1.  3.4 4.8]]


In [11]:
#  Get Dimsension 
c.ndim

2

In [12]:
#  Get Shape
c.shape

(2, 3)

In [13]:
#  Get Type 
b.dtype

dtype('int64')

In [14]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype= 'int16')
d.dtype

dtype('int16')

In [15]:
#  Get Size 
print(a.itemsize)
print(d.itemsize)

8
2


In [16]:
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# Get Total Size
print(a.size*a.itemsize)
print(b.size*b.itemsize)
print(c.size*c.itemsize)
print(d.size*d.itemsize)

24
24
48
18


or...


In [18]:
# Get Total Size 

print(a.nbytes)
print(b.nbytes)
print(c.nbytes)
print(d.nbytes)

24
24
48
18


Initializing Different Types of Array

In [19]:
#  All 0s Matrix

np.zeros((2,3,3,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [20]:
#  All 1s Matrix

np.ones((2,3,3,5), dtype='int32')

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int32)

In [21]:
# Any other numbers -> ((shape),(number))

np.full((2,3,5,4),(88))

array([[[[88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88]],

        [[88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88]],

        [[88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88]]],


       [[[88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88]],

        [[88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88]],

        [[88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88],
         [88, 88, 88, 88]]]])

In [22]:
# Any other numbers -> (full_like)

np.full((d.shape), (4,5,6))

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

or...

In [23]:
# Any other numbers -> (full_like)

np.full_like(d, (4,5,6))

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]], dtype=int16)

In [24]:
#  Random Decimal Numbers

np.random.rand(4,2,3)

array([[[7.43738754e-01, 3.49554709e-01, 2.81828305e-01],
        [3.23475316e-01, 8.96703397e-01, 7.78134817e-01]],

       [[3.75253227e-01, 8.24842694e-01, 7.61657366e-01],
        [8.65597080e-04, 8.89106196e-01, 5.34225642e-01]],

       [[2.34612299e-01, 5.50186005e-01, 5.31586702e-01],
        [3.63475068e-01, 4.93186494e-01, 8.06420241e-02]],

       [[2.28815713e-01, 4.14059484e-01, 7.90776565e-01],
        [4.24596801e-01, 9.72128551e-01, 6.34722989e-01]]])

In [25]:
np.random.sample(d.shape)

array([[0.562713  , 0.39369612, 0.85473458],
       [0.64763193, 0.01319753, 0.18983247],
       [0.36925276, 0.95005069, 0.34497139]])

In [26]:
#  Array in the range [10, 20) with values (4, 2, 3)

w_uniform = np.random.uniform(low=10.0, high=20.0, size=(4, 2, 3))
w_uniform

array([[[13.02045446, 10.25037572, 11.12331111],
        [16.21891693, 12.39969396, 18.98508123]],

       [[16.79192487, 15.45191684, 18.33829535],
        [11.01850224, 19.08966246, 19.53130515]],

       [[19.12033186, 12.62334257, 13.42741033],
        [13.41724366, 19.7963383 , 10.81860601]],

       [[15.17371891, 11.47598391, 11.61890803],
        [12.09504836, 10.50046764, 12.69113437]]])

In [27]:
#  Random Integer Values

np.random.randint(88,140, size=(3,4,7))

array([[[121, 129,  95, 121, 135, 120,  90],
        [ 91, 129,  96, 133, 109, 130, 128],
        [122, 111, 135, 114, 123, 131, 102],
        [100,  89, 124,  99,  97, 127, 122]],

       [[132, 135, 107, 116, 131, 128, 122],
        [113, 132, 103, 139,  89,  96, 133],
        [135,  94, 107, 124,  95,  96,  99],
        [121, 131, 138, 118, 114, 114, 117]],

       [[117, 133, 107, 125, 113, 110,  90],
        [ 90, 109, 126, 112, 111, 133, 110],
        [133,  97, 110, 138, 131, 114, 135],
        [ 97, 112, 122, 128, 128, 102, 127]]], dtype=int32)

In [28]:
#  The Identity Matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
#  Repeat an array

arr= np.array([[1,2,3],[2,3,4],[3,4,5]])
R1=np.repeat(arr,3, axis=0)
print(R1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [2 3 4]
 [2 3 4]
 [2 3 4]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [30]:
x=np.ones((5,5))
print(x)

z=np.zeros((3,3))
z[1,1]=9
print(z)

x[1:-1,1:-1]=z
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be Careful When Copying Arrays!!!

In [31]:
s=[[1,2,3],[4,5,6]]
h=s.copy()
h[0]=[100,32,198] 
print(h)
print(s)

[[100, 32, 198], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6]]


##### Reorganizing Arrays

In [39]:
before= np.array([[1,2,3,4],[5,6,7,8]])
print(before)


after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
#  Vertically Stacking Vectors

v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])

print(np.vstack([v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]


In [44]:
#  Horizonal stacking Vectors

v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])

print(np.hstack([v1,v2]))

[1 2 3 4 5 6 7 8]


Micellaneous

Load a data from a file

In [50]:
dt= np.genfromtxt("data.txt", delimiter=",")
print(dt)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [53]:
print(dt.astype("int32"))

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Advanced Indexing and Boolean Masking

In [56]:
print(dt[dt>50])

[196.  75. 766.  75.  55. 999.  78.  76.  88.]


You can index with a list in NumPy

In [58]:
j= np.array([1,2,3,4,5,6,7,8,9,10])

print(j[[1,5,7]])

[2 6 8]


In [ ]:
np.any(dt>50, axis=0)  #The transaction takes place line by row.

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [64]:
np.any(dt>50, axis=1)  #The transaction takes place line by columns.

array([ True,  True,  True])

In [65]:
((dt<100) & (dt>50))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])