Accessing/Changing specific elements, rows,columns... etc

In [2]:
import numpy as np

In [8]:
x=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]], dtype= 'int16')
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
#  Get a spesific element [r,c]

x[1,5]

np.int16(13)

In [13]:
# Get a spesific row

x[0,:]

array([1, 2, 3, 4, 5, 6, 7], dtype=int16)

In [15]:
# Get a spesific column

x[:,6]

array([ 7, 14], dtype=int16)

In [18]:
# Getting a little more fantasy [startindex:endindex;stepsize]

x[1, 0:5:2]

array([ 8, 10, 12], dtype=int16)

In [20]:
#  Change elements

x[1,4]=25 
print(x)

x[:,2]=5
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 25 13 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 25 13 14]]


In [26]:
y= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
#  Get a spesific element [work outside in]]
print(y[0,1,1])

4


In [33]:
# Replace

y[:,1,:]=[[8,8],[9,9]]
print(y[:,1,:])
print(y)

[[8 8]
 [9 9]]
[[[1 2]
  [8 8]]

 [[5 6]
  [9 9]]]
